### ISSUE TITLE
怎么提交自己的 Web 前端开源库？

### ISSUE THREAD

**Issue by TechQuery** [bootcdn/BootCDN#1]
用 Wiki 写个文档吧~

**Comment by wangsai** [comment]
Hello, @TechQuery ，这个仓库存在的目的是修正 cdnjs 仓库中某些文件的错误或针对国内情况修改某些文件。例如：有的项目在css文件中引入了google font，这个在国内用不了，因此需要清洗；还有比如将 twitter-bootstrap 正名为 bootstrap；等等

如果需要提交自己的开源库的话，建议去  cdnjs 提交，这样凡是和 BootCDN 一样以 cdnjs 为源的免费cdn就都能够提供加速了。

**Comment by TechQuery** [comment]
CDNJS 的入选要求 暂时达不到……

我开发的开源库 都放在 [Git@OSC](//git.oschina.net/Tech_Query)

**Comment by wangsai** [comment]
建议转 github 吧，git@osc 老外更不认。

建议把你的库放到社区中供大家测试，多听听反馈，好东西一定能得到大家的认可！

**Comment by wangsai** [comment]
目前同步cdnjs是最合适的选择！！！

- 首先，国内能够做的比较成功（以用户量来评判）的开源前端库非常罕见，大家平时使用的大量工具库都是老外开发并维护的，所以自建仓库的话最后也是 99.999% 和 cdnjs 一模一样， 落得重复造轮子。
- 其次，自己维护一个仓库需要的工作量很大，能够愿意投入自己的业余时间并坚持做维护工作的小伙伴很难找。君不见大量虎头蛇尾的国产项目荒废吗。比如 [staticfile.org](https://github.com/staticfile/static/issues) 就废了，连 @qiniu 号称拿了上亿美金投资的公司都舍不得投入一个人力来维护了！

有价值的事情很多很多，可是个人经历／财力／能力有限。目前我每天会抽出一点儿时间维护并改进  BootCDN ，这份事情我已经坚持了3年了，望君体谅！

**Comment by TechQuery** [comment]
莫激动……

我说的是“自建**国内**开源项目仓库”，而 StaticFile.org 的国际部分只是对 CDNjs 的仓库做了个**镜像引用**，并没有复制过来，仅为**国内网络环境**做代理加速。

**Comment by wangsai** [comment]
呵呵，即便建一个专门针对国内的开源项目仓库，试问，如何设定收录规则？cdnjs规定 github star 需要达到一定数量才能收录，如果照这个标准的话，国内能有多少前端库符合要求？

如果量很大的话，维护成本高，如果量很少的话， 何必呢

**Comment by TechQuery** [comment]
在 GitHub 上与国际同行多交流 —— 必不可少；
Git@OSC 等国内平台上的开源发展 —— 也不可忽视

**Comment by wangsai** [comment]
支持你的观点！

但是我只用 github

**Comment by TechQuery** [comment]
> 如果量很大的话，维护成本高，如果量很少的话， 何必呢

@wangsai 只有像标准 polyfill 这样的特定领域前端库才需要人工维护白名单，而且量很小，好维护：JSCIG/es-discuss#34

但不特定的所有前端库，应该像 JSDelivr、 unpkg 那样全量镜像 NPM，虽然量大，但只是消耗云资源，自动化也不需要人工维护，有什么安全问题的库上游都会及时删除。
