### ISSUE TITLE
请添加qrcodejs

### ISSUE THREAD

**Issue by ryh** [bootcdn/BootCDN#4]
（因为没有tag/release 所以这个cdnjs上High Priority的issue一直没完成）`#5164 #9878 #11069`
Library name: qrcodejs
Git repository url: https://github.com/davidshimjs/qrcodejs
npm package name or url (if there is one):
License (List them all if it's multiple): MIT
Official homepage: https://github.com/davidshimjs/qrcodejs
Wanna say something? Leave message here:
This QRCode.js has no dependencies.

**Comment by wangsai** [comment]
已经添加了。

http://www.bootcdn.cn/qrcode-generator/

**Comment by ryh** [comment]
@wangsai  404 而且看名字和版本号应该是另外一个npm上的库（这个我在cdnjs发了add request了）`https://github.com/cdnjs/cdnjs/issues/11070`
```
curl -i https://cdn.bootcss.com/qrcode-generator/1.2.0/qrcode.js

HTTP/2 404
server: marco/0.27
date: Mon, 17 Apr 2017 12:41:10 GMT
content-type: text/html
content-length: 568
vary: Accept-Encoding
access-control-allow-origin: *
x-request-id: 8fae1f85b936fdf35c79a64f21fffef7; 08eaf073c35d2f99674153c89b352fba
x-source: U/404
expires: Mon, 17 Apr 2017 12:45:37 GMT
cache-control: max-age=300
age: 33
x-cache: MISS from 403-zj-fud-208, MISS from mix-sd-tna-134; HIT(R) from ctn-sc-mei-133
via: T.5203.M.1, V.403-zj-fud-208, S.mix-sd-tna-136, T.216134.M.1, V.mix-sd-tna-134, T.118132.R.1, M.ctn-sc-mei-133
```

**Comment by wangsai** [comment]
davidshimjs/qrcodejs 没有 tag、version，在 npm 上也什么都没有，无法添加。

kazuhikoarase/qrcode-generator 在 npm 上有连续的版本发布，还好一些。所以只能添加这个。
cdnjs 如果接受的话也只会接受这个

**Comment by ryh** [comment]
好吧
